version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jewelry
    ports:
      - '5432:5432'
  api:
    build: ./backend
    command: npm run dev
    volumes:
      - ./backend:/app
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: jewelry
    depends_on:
      - db
